title: "Software for the 2.7m Harlan J Smith Telescope, McDonald Observatory, The University of Texas"
description: "Open-source software packages for telescope control, instrument control, and data reduction"
theme: jekyll-theme-cayman
